quarkus:
  datasource:
    username: bob
    password: bob
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/smartbarbo
  hibernate-orm:
    database:
      generation: drop-and-create
